Repository SSA-FY/frontend, pull requests merged in 2024-06, with the labels that each got.

#6 feat: add Common Button and Modal
  src/components/BottomOrangeButton.vue
  src/components/TopBackward.vue
  src/components/modals/Confirm.vue
Labels: ✨ feature, 🎨 style

#11 UI & API: MainPage(Home)과 SignupPage 구현과 로그인 기능
  package-lock.json
  package.json
  postcss.config.js
  src/App.vue
  src/assets/.gitkeep
  src/assets/reset.css
  src/components/.gitkeep
  src/components/Confetti.vue
  src/components/logos/Google.vue
  src/components/logos/Kakao.vue
  src/components/logos/LogoMark.vue
  src/components/logos/LogoText.vue
  src/components/logos/Naver.vue
  src/router/index.js
  src/stores/.gitkeep
  src/stores/memberStore.js
  src/utils/axios.js
  src/views/.gitkeep
  src/views/Index.vue
  src/views/member/Login.vue
  src/views/member/Signup.vue
  src/views/member/SignupSuccess.vue
  tailwind.config.js
Labels: ✨ feature

#12 feat & UI: add group-related pages
  src/assets/imgs/addMember.svg
  src/assets/imgs/chevron.svg
  src/assets/imgs/close.svg
  src/assets/imgs/docPencil.svg
  src/assets/imgs/edit.svg
  src/assets/imgs/leave.svg
  src/assets/imgs/picture.svg
  src/assets/imgs/success.svg
  src/components/TopBackward.vue
  src/components/modals/Confirm.vue
  src/components/modals/MemberInvite.vue
  src/components/modals/SimpleOk.vue
  src/components/modals/SingleOk.vue
  src/views/group/Create.vue
  src/views/group/CreateSuccess.vue
  src/views/group/Detail.vue
  src/views/group/Edit.vue
  src/views/notification/Invitation.vue
Labels: ✨ feature, 🎨 style

#14 feat & UI & API: add Create, Vote pages with Components
  package-lock.json
  package.json
  src/apis/vote.js
  src/components/Urls.vue
  src/components/vote/create/SuggestVoteItem.vue
  src/components/vote/create/Suggestions.vue
  src/components/vote/create/VoteButton.vue
  src/components/vote/finish/Finish.vue
  src/components/vote/vote/MemberItem.vue
  src/components/vote/vote/MemberList.vue
  src/components/vote/vote/MemberResultItem.vue
  src/components/vote/vote/TopBackward.vue
  src/components/vote/vote/VoteContents.vue
  src/components/vote/vote/background.jpg
  src/router/index.js
  src/views/vote/Create.vue
  src/views/vote/Finish.vue
  src/views/vote/Vote.vue
Labels: ✨ feature

#15 UI: 메인페이지, 알림페이지 화면 개발
  src/assets/imgs/bell-svgrepo-com.svg
  src/assets/imgs/default-img.webp
  src/assets/imgs/invitation-img.svg
  src/assets/imgs/person-svgrepo-com.svg
  src/assets/imgs/vote-result-img.svg
  src/components/common/NavBar.vue
  src/components/group/GroupItem.vue
  src/components/notification/NotificationItem.vue
  src/components/notification/NotificationVoteItem.vue
  src/components/notification/VoteOpenModal.vue
  src/views/group/Group.vue
  src/views/notification/Notification.vue
  src/views/notification/Vote.vue
Labels: ✨ feature

#18 [API] VoteAPI 버그 피스
  src/apis/vote.js
  src/components/vote/vote/MemberItem.vue
  src/components/vote/vote/MemberList.vue
  src/components/vote/vote/MemberResultItem.vue
  src/views/vote/Create.vue
  src/views/vote/Vote.vue
Labels: 🔨 fix, ♻️ refactor

#24 [UI, API] 지난 투표 화면 개발 및 투표 화면 일관성 개선과 추가 API연동
  src/apis/board.js
  src/apis/comment.js
  src/apis/vote.js
  src/components/board/Comment.vue
  src/components/board/VoteResultItem.vue
  src/components/vote/create/VoteButton.vue
  src/components/vote/finish/Finish.vue
  src/components/vote/vote/MemberItem.vue
  src/components/vote/vote/MemberList.vue
  src/components/vote/vote/NoVote.vue
  src/components/vote/vote/VoteContents.vue
  src/router/index.js
  src/views/board/Detail.vue
  src/views/board/List.vue
  src/views/vote/Create.vue
  src/views/vote/Vote.vue
Labels: ✨ feature

#25 feat & API: develop group creating pages
  src/apis/group.js
  src/apis/invite.js
  src/assets/imgs/logo_circle_800.png
  src/components/Confetti.vue
  src/components/common/NavBar.vue
  src/components/modals/Confirm.vue
  src/components/modals/MemberInvite.vue
  src/views/group/Create.vue
  src/views/group/CreateSuccess.vue
  src/views/group/Group.vue
Labels: ✨ feature

#28 API: develop group detail page
  src/apis/group.js
  src/apis/invite.js
  src/views/group/Create.vue
  src/views/group/CreateSuccess.vue
  src/views/group/Detail.vue
Labels: ✨ feature, 🔨 fix
